import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';
import { getEnrollmentByUserAndCourse } from '../models/enrollmentModel.js';
import { createCertificate, updateCertificateFilePath, certificateExists } from '../models/certificateModel.js';
import { format } from 'date-fns';


export const generateCertificate = async (userId, courseId) => {
  try {
    // Check if certificate already exists
    const exists = await certificateExists(userId, courseId);
    if (exists) {
      console.log(`Certificate already exists for user ${userId} and course ${courseId}`);
      return { message: 'Certificate already exists' };
    }

    const enrollment = await getEnrollmentByUserAndCourse(userId, courseId);

    if (!enrollment || !enrollment.completed) {
      throw new Error('Certificate can only be generated for completed enrollments.');
    }

    // Generate unique certificate ID
    const certificateId = `CERT-${Date.now()}-${userId}-${courseId}`;
    const fileName = `${certificateId}.pdf`;
    const filePath = path.join('uploads', 'certificates', fileName);

   
    fs.mkdirSync(path.dirname(filePath), { recursive: true });

   
    const doc = new PDFDocument({
      size: 'A4',
      layout: 'landscape',
      margins: { top: 50, bottom: 50, left: 72, right: 72 }
    });

    const writeStream = fs.createWriteStream(filePath);
    doc.pipe(writeStream);

    // Enhanced PDF design
    // Background
    doc.rect(0, 0, doc.page.width, doc.page.height)
       .fill('#ffffff');

    // Border
    const margin = 40;
    doc.rect(margin, margin, doc.page.width - 2 * margin, doc.page.height - 2 * margin)
       .stroke('#007BFF')
       .lineWidth(4);

    // Inner decorative border
    doc.rect(margin + 20, margin + 20, doc.page.width - 2 * (margin + 20), doc.page.height - 2 * (margin + 20))
       .stroke('#28a745')
       .lineWidth(1);

    // Header
    doc.fillColor('#007BFF')
       .fontSize(32)
       .font('Times-Bold')
       .text('🎓 CERTIFICATE OF COMPLETION', {
         align: 'center',
         y: 120
       });

    // Decorative line
    const centerX = doc.page.width / 2;
    doc.moveTo(centerX - 200, 180)
       .lineTo(centerX + 200, 180)
       .stroke('#28a745')
       .lineWidth(3);

    // Presented to text
    doc.fillColor('#2c3e50')
       .fontSize(24)
       .font('Helvetica')
       .text('This certifies that', {
         align: 'center',
         y: 220
       });

    // Student name (highlighted)
    doc.fillColor('#007BFF')
       .fontSize(36)
       .font('Times-Bold')
       .text(enrollment.student_name, {
         align: 'center',
         y: 270
       });

    // Course completion text
    doc.fillColor('#2c3e50')
       .fontSize(22)
       .font('Helvetica')
       .text('has successfully completed the course', {
         align: 'center',
         y: 330
       });

    // Course title (highlighted)
    doc.fillColor('#28a745')
       .fontSize(28)
       .font('Helvetica-Bold')
       .text(`"${enrollment.course_title}"`, {
         align: 'center',
         y: 380
       });

    // Date and instructor info
    const formattedDate = format(new Date(enrollment.completed_at), 'MMMM dd, yyyy');
    doc.fillColor('#6c757d')
       .fontSize(16)
       .font('Helvetica')
       .text(`Completed on: ${formattedDate}`, {
         align: 'center',
         y: 440
       });

    if (enrollment.instructor_name) {
      doc.text(`Instructor: ${enrollment.instructor_name}`, {
        align: 'center',
        y: 470
      });
    }

    // Certificate ID for verification
    doc.fontSize(12)
       .fillColor('#95a5a6')
       .text(`Certificate ID: ${certificateId}`, {
         align: 'center',
         y: 500
       });

    // Footer
    doc.fontSize(10)
       .text('This certificate was automatically generated by LearnHub LMS', {
         align: 'center',
         y: 530
       });

    // Add some decorative elements
    // Left corner decoration
    doc.circle(80, 120, 10).fill('#007BFF');
    doc.circle(100, 140, 8).fill('#28a745');
    
    // Right corner decoration
    doc.circle(doc.page.width - 80, 120, 10).fill('#007BFF');
    doc.circle(doc.page.width - 100, 140, 8).fill('#28a745');

    doc.end();

    return new Promise(async (resolve, reject) => {
      writeStream.on('finish', async () => {
        try {
          // Save certificate record to database
          const certificate = await createCertificate(userId, courseId, {
            certificateId,
            filePath: `/uploads/certificates/${fileName}`,
            finalGrade: enrollment.final_grade || null
          });
          
          console.log(`Certificate generated successfully for user ${userId}, course ${courseId}`);
          
          resolve({ 
            certificate,
            filePath,
            fileName,
            downloadUrl: `/uploads/certificates/${fileName}`,
            certificateId
          });
        } catch (dbError) {
          console.error('Database save error:', dbError);
          // Still return file info even if DB fails
          resolve({ 
            filePath, 
            fileName, 
            downloadUrl: `/uploads/certificates/${fileName}`,
            certificateId,
            warning: 'Certificate file created but database record failed'
          });
        }
      });
      
      writeStream.on('error', (error) => {
        console.error('Certificate file creation error:', error);
        reject(error);
      });
    });
  } catch (error) {
    console.error('Certificate generation failed:', error.message);
    throw error;
  }
};
